# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json
#   timestamp: 2022-12-31T17:02:53+00:00

from __future__ import annotations

from typing import Any

from hera import BaseModel


class Model(BaseModel):
    __root__: Any
