# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/master/api/openapi-spec/swagger.json
#   timestamp: 2022-12-30T03:41:10+00:00

from __future__ import annotations

from typing import Annotated, Optional

from pydantic import Field

from hera import ArgoBaseModel

from .io.argoproj.events import v1alpha1
from .io.k8s.apimachinery.pkg.apis.meta import v1


class EventSourceDeletedResponse(ArgoBaseModel):
    pass


class LogEntry(ArgoBaseModel):
    event_name: Annotated[
        Optional[str], Field(alias='eventName', title='optional - the event name (e.g. `example`)')
    ] = None
    event_source_name: Annotated[Optional[str], Field(alias='eventSourceName')] = None
    event_source_type: Annotated[
        Optional[str], Field(alias='eventSourceType', title='optional - the event source type (e.g. `webhook`)')
    ] = None
    level: Optional[str] = None
    msg: Optional[str] = None
    namespace: Optional[str] = None
    time: Optional[v1.Time] = None


class CreateEventSourceRequest(ArgoBaseModel):
    event_source: Annotated[Optional[v1alpha1.EventSource], Field(alias='eventSource')] = None
    namespace: Optional[str] = None


class EventSourceWatchEvent(ArgoBaseModel):
    object: Optional[v1alpha1.EventSource] = None
    type: Optional[str] = None


class UpdateEventSourceRequest(ArgoBaseModel):
    event_source: Annotated[Optional[v1alpha1.EventSource], Field(alias='eventSource')] = None
    name: Optional[str] = None
    namespace: Optional[str] = None
