apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: plugin-artifact-
spec:
  entrypoint: steps
  templates:
  - name: steps
    steps:
    - - name: emit-sbom
        template: emit-sbom
  - name: emit-sbom
    outputs:
      artifacts:
      - name: image-sbom
        path: /tmp/sbom.json
        archive:
          none: {}
        plugin:
          name: oras
          configuration: 'image: registry.example.com/my-image:latest'
          key: sbom
    script:
      image: python:3.10
      source: |-
        import os
        import sys
        sys.path.append(os.getcwd())
        with open('/tmp/sbom.json', 'w') as f:
            f.write('{"format": "spdx"}')
      command:
      - python
