# generated by datamodel-codegen:
#   filename:  argo-workflows-3.7.3.json

from __future__ import annotations

from typing import Annotated

from pydantic import Field

from hera.shared._pydantic import APIBaseModel

from .github.com.argoproj.argo_events.pkg.apis.events import v1alpha1
from .io.k8s.apimachinery.pkg.apis.meta import v1


class EventSourceDeletedResponse(APIBaseModel):
    pass


class LogEntry(APIBaseModel):
    event_name: Annotated[
        str | None,
        Field(alias="eventName", title="optional - the event name (e.g. `example`)"),
    ] = None
    event_source_name: Annotated[str | None, Field(alias="eventSourceName")] = None
    event_source_type: Annotated[
        str | None,
        Field(
            alias="eventSourceType",
            title="optional - the event source type (e.g. `webhook`)",
        ),
    ] = None
    level: str | None = None
    msg: str | None = None
    namespace: str | None = None
    time: v1.Time | None = None


class CreateEventSourceRequest(APIBaseModel):
    event_source: Annotated[v1alpha1.EventSource | None, Field(alias="eventSource")] = None
    namespace: str | None = None


class EventSourceWatchEvent(APIBaseModel):
    object: v1alpha1.EventSource | None = None
    type: str | None = None


class UpdateEventSourceRequest(APIBaseModel):
    event_source: Annotated[v1alpha1.EventSource | None, Field(alias="eventSource")] = None
    name: str | None = None
    namespace: str | None = None
