# generated by datamodel-codegen:
#   filename:  argo-workflows-3.7.3.json

from __future__ import annotations

from typing import Annotated

from hera.shared._pydantic import BaseModel, Field

from .github.com.argoproj.argo_events.pkg.apis.events import v1alpha1
from .io.k8s.apimachinery.pkg.apis.meta import v1


class DeleteSensorResponse(BaseModel):
    pass


class LogEntry(BaseModel):
    dependency_name: Annotated[
        str | None,
        Field(alias="dependencyName", title="optional - trigger dependency name"),
    ] = None
    event_context: Annotated[str | None, Field(alias="eventContext", title="optional - Cloud Event context")] = None
    level: str | None = None
    msg: str | None = None
    namespace: str | None = None
    sensor_name: Annotated[str | None, Field(alias="sensorName")] = None
    time: v1.Time | None = None
    trigger_name: Annotated[str | None, Field(alias="triggerName", title="optional - any trigger name")] = None


class CreateSensorRequest(BaseModel):
    create_options: Annotated[v1.CreateOptions | None, Field(alias="createOptions")] = None
    namespace: str | None = None
    sensor: v1alpha1.Sensor | None = None


class SensorWatchEvent(BaseModel):
    object: v1alpha1.Sensor | None = None
    type: str | None = None


class UpdateSensorRequest(BaseModel):
    name: str | None = None
    namespace: str | None = None
    sensor: v1alpha1.Sensor | None = None
