# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.4/api/openapi-spec/swagger.json
#   timestamp: 2023-02-08T02:43:34+00:00

from __future__ import annotations

from typing import Optional

from hera.events._base_model import BaseModel


class Any(BaseModel):
    type_url: Optional[str] = None
    value: Optional[str] = None
