# generated by datamodel-codegen:
#   filename:  spec.json

from __future__ import annotations

from typing import Optional

from hera.shared._base_model import BaseModel


class Any(BaseModel):
    type_url: Optional[str] = None
    value: Optional[str] = None
