# generated by datamodel-codegen:
#   filename:  argo-workflows-3.7.3.json

from __future__ import annotations

from pydantic import Base64Str

from hera.shared._pydantic import APIBaseModel


class Any(APIBaseModel):
    type_url: str | None = None
    value: Base64Str | None = None
