from hera.workflows import Container, Script, Step, Steps, Workflow
from hera.workflows.models import Arguments, Inputs, Item, Outputs, Parameter, ValueFrom

with Workflow(
    api_version="argoproj.io/v1alpha1",
    kind="Workflow",
    generate_name="parameter-aggregation-",
    entrypoint="parameter-aggregation",
) as w:
    with Steps(
        name="parameter-aggregation",
    ) as invocator:
        Step(
            with_items=[
                Item(
                    __root__=1,
                ),
                Item(
                    __root__=2,
                ),
                Item(
                    __root__=3,
                ),
                Item(
                    __root__=4,
                ),
            ],
            arguments=Arguments(
                parameters=[
                    Parameter(
                        name="num",
                        value="{{item}}",
                    )
                ],
            ),
            name="odd-or-even",
            template="odd-or-even",
        )
        Step(
            arguments=Arguments(
                parameters=[
                    Parameter(
                        name="message",
                        value="{{steps.odd-or-even.outputs.parameters.num}}",
                    )
                ],
            ),
            name="print-nums",
            template="print-message",
        )
        Step(
            arguments=Arguments(
                parameters=[
                    Parameter(
                        name="message",
                        value="{{steps.odd-or-even.outputs.parameters.evenness}}",
                    )
                ],
            ),
            name="print-evenness",
            template="print-message",
        )
        Step(
            with_param="{{steps.odd-or-even.outputs.parameters}}",
            arguments=Arguments(
                parameters=[
                    Parameter(
                        name="num",
                        value="{{item.num}}",
                    )
                ],
            ),
            name="divide-by-2",
            template="divide-by-2",
            when="{{item.evenness}} == even",
        )
        Step(
            with_param="{{steps.divide-by-2.outputs.result}}",
            arguments=Arguments(
                parameters=[
                    Parameter(
                        name="message",
                        value="{{item}}",
                    )
                ],
            ),
            name="print",
            template="print-message",
        )
    Container(
        inputs=Inputs(
            parameters=[
                Parameter(
                    name="num",
                )
            ],
        ),
        name="odd-or-even",
        outputs=Outputs(
            parameters=[
                Parameter(
                    name="num",
                    value_from=ValueFrom(
                        path="/tmp/num",
                    ),
                ),
                Parameter(
                    name="evenness",
                    value_from=ValueFrom(
                        path="/tmp/even",
                    ),
                ),
            ],
        ),
        args=[
            'sleep 1 &&\necho {{inputs.parameters.num}} > /tmp/num &&\nif [ $(({{inputs.parameters.num}}%2)) -eq 0 ]; then\n  echo "even" > /tmp/even;\nelse\n  echo "odd" > /tmp/even;\nfi\n'
        ],
        command=["sh", "-xc"],
        image="alpine:latest",
    )
    Script(
        inputs=Inputs(
            parameters=[
                Parameter(
                    name="num",
                )
            ],
        ),
        name="divide-by-2",
        command=["sh", "-x"],
        image="alpine:latest",
        source="#!/bin/sh\necho $(({{inputs.parameters.num}}/2))\n",
    )
    Container(
        inputs=Inputs(
            parameters=[
                Parameter(
                    name="message",
                )
            ],
        ),
        name="print-message",
        args=["{{inputs.parameters.message}}"],
        command=["echo"],
        image="busybox",
    )
