# generated by datamodel-codegen:
#   filename:  argo-workflows-3.4.4.json

from __future__ import annotations

from hera.shared._pydantic import BaseModel


class IntOrString(BaseModel):
    __root__: str
