# generated by datamodel-codegen:
#   filename:  argo-workflows-4.0.5.json

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import Field

from hera.shared._pydantic import APIBaseModel


class SyncConfigType(Enum):
    configmap = "CONFIGMAP"
    database = "DATABASE"


class DeleteSyncLimitResponse(APIBaseModel):
    pass


class CreateSyncLimitRequest(APIBaseModel):
    cm_name: Annotated[str | None, Field(alias="cmName")] = None
    key: str | None = None
    limit: int | None = None
    namespace: str | None = None
    type: SyncConfigType | None = "CONFIGMAP"


class SyncLimitResponse(APIBaseModel):
    cm_name: Annotated[str | None, Field(alias="cmName")] = None
    key: str | None = None
    limit: int | None = None
    namespace: str | None = None
    type: SyncConfigType | None = "CONFIGMAP"


class UpdateSyncLimitRequest(APIBaseModel):
    cm_name: Annotated[str | None, Field(alias="cmName")] = None
    key: str | None = None
    limit: int | None = None
    namespace: str | None = None
    type: SyncConfigType | None = "CONFIGMAP"
