# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.4/api/openapi-spec/swagger.json
#   timestamp: 2023-02-08T02:49:18+00:00

from __future__ import annotations

from hera.workflows._base_model import BaseModel


class IntOrString(BaseModel):
    __root__: str
