# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.4/api/openapi-spec/swagger.json

from __future__ import annotations

from hera.shared._base_model import BaseModel


class IntOrString(BaseModel):
    __root__: str
