# generated by datamodel-codegen:
#   filename:  argo-workflows-4.0.5.json

from __future__ import annotations

from pydantic import RootModel


class IntOrString(RootModel[str | int]):
    root: str | int
