# generated by datamodel-codegen:
#   filename:  argo-workflows-3.7.3.json

from __future__ import annotations

from hera.shared._pydantic import BaseModel

from ...google import protobuf


class Error(BaseModel):
    code: int | None = None
    details: list[protobuf.Any] | None = None
    error: str | None = None
    message: str | None = None


class StreamError(BaseModel):
    details: list[protobuf.Any] | None = None
    grpc_code: int | None = None
    http_code: int | None = None
    http_status: str | None = None
    message: str | None = None
